# Generated by Django 5.1.4 on 2024-12-13 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('periodic_table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Discovery Date')),
                ('type', models.CharField(choices=[('S', 'Synthesized'), ('N', 'Naturally Found'), ('D', 'Discovered')], default='S', max_length=1)),
                ('discoverer', models.CharField(max_length=100, verbose_name='Discoverer')),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='periodic_table.element')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
